const Routes = {
  // EXAMPLE: require("your path") | File
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  Work_Out: 'Work_out',
  Meal_Plan: 'MEAL_PLAN',
  SOUND: 'SOUND',
  DASHBOARD_STACK: 'DASHBOARD_STACK',
  AUTH_STACK: 'AUTH_STACK',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  SPREADCLR: 'SPREADCLR',
  EDITPROFLE: 'EDITPROFLE',
  FULLSCREEN: 'FULLSCREEN',
};
export default Routes;
