const Routes = {
  // EXAMPLE: require("your path") | File
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  DASHBOARD_STACK: 'DASHBOARD_STACK',
  AUTH_STACK: 'AUTH_STACK',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
};
export default Routes;
